---
title: "p8105_hw1_jw4690"
output: github_document
date: "2024-09-12"
author: "Jingxi Wang"
---

```{r}
library(tidyverse)
```


## Problem 1

```{r penguins}

library(palmerpenguins)

data("penguins", package = "palmerpenguins")
```

The key variables are `species`, `island`, `bill_length_mm`, `bill_depth_mm`, `flipper_length_mm`, `body_mass_g`, `sex`, and `year`.

The penguins dataset has `r nrow(penguins)` rows, `r ncol(penguins)` columns.

The mean of the flipper length is `r mean(penguins$flipper_length_mm, na.rm = TRUE)` mm.

```{r scatterplot}

ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point() 

ggsave("penguins_scatterplot.png", device = "png")
```


## Problem 2

```{r}

p2_df = 
  tibble(
    sample_normal_dis = rnorm(10),
    logical_vector = rnorm(10) > 0,
    character_vector = letters[1:10],
    factor_vector = factor(rep(c("Lv1", "Lv2", "Lv3"), length.out = 10))
  )
```

```{r}
mean(pull(p2_df, var = sample_normal_dis, name = NULL))

mean(pull(p2_df, var = logical_vector, name = NULL))

mean(pull(p2_df, var = character_vector, name = NULL))

mean(pull(p2_df, var = factor_vector, name = NULL))
```

